# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dramaorg.models


class Migration(migrations.Migration):

    replaces = [('dramaorg', '0001_initial'), ('dramaorg', '0002_user_token_expiry'), ('dramaorg', '0003_user_pgps_squashed_0007_auto_20170710_1249'), ('dramaorg', '0004_auto_20170710_1549'), ('dramaorg', '0005_groupproxy'), ('dramaorg', '0006_auto_20170710_1835'), ('dramaorg', '0007_space_include_building_name'), ('dramaorg', '0008_auto_20170710_2203')]

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('login_token', models.CharField(default=dramaorg.models.generate_token, max_length=86)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('year', models.PositiveSmallIntegerField(default=dramaorg.models._get_year)),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3)),
                ('slug', models.SlugField(unique=True)),
                ('invisible', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='pgps',
            field=models.CharField(blank=True, max_length=20, verbose_name='Preferred Gender Pronouns'),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Building')),
                ('include_building_name', models.BooleanField(default=True, help_text='uncheck this to hide the building name when displaying the full name of the space')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Space'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='staff',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
