# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0001_initial_squashed_0008_auto_20170710_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(default='default', editable=False, max_length=20),
        ),
    ]
