# Generated by Django 2.0 on 2017-12-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0001_initial_squashed_0008_auto_20170710_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(default='default', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='show',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dramaorg.Space'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
