# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
