# Generated by Django 2.0 on 2017-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0002_auto_20171228_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(default='Harvard College', max_length=160, verbose_name='School or Affiliation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Graduation Year'),
        ),
    ]
