# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dramaorg', '0003_user_pgps'), ('dramaorg', '0004_auto_20170709_2249'), ('dramaorg', '0005_space'), ('dramaorg', '0006_show_space'), ('dramaorg', '0007_auto_20170710_1249')]

    dependencies = [
        ('dramaorg', '0002_user_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pgps',
            field=models.CharField(blank=True, max_length=20, verbose_name='Preferred Gender Pronouns'),
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('building', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Space'),
            preserve_default=False,
        ),
    ]
