# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0002_user_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pgps',
            field=models.CharField(default='', max_length=20, verbose_name='Preferred Pronouns'),
            preserve_default=False,
        ),
    ]
