# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0003_user_pgps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pgps',
            field=models.CharField(blank=True, max_length=20, verbose_name='Preferred Gender Pronouns'),
        ),
    ]
