# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0003_user_pgps_squashed_0007_auto_20170710_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='staff',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
