# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0003_auto_20170712_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
    ]
