# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0004_auto_20170709_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('building', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
