# Generated by Django 2.0 on 2017-12-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0004_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dramaorg.Space'),
        ),
    ]
