# Generated by Django 2.0 on 2018-01-02 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0004_auto_20171230_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dramaorg.Space', verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_index=True, max_length=80),
        ),
    ]
