# Generated by Django 2.0 on 2018-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0005_auto_20180101_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='residency_ends',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='residency_starts',
            field=models.DateField(null=True),
        ),
    ]
