# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0005_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Space'),
            preserve_default=False,
        ),
    ]
