# Generated by Django 2.0 on 2018-01-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0006_auto_20180106_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_pref',
            field=models.CharField(blank=True, max_length=30, verbose_name='Preferred Stage Gender'),
        ),
    ]
