# Generated by Django 2.1 on 2018-08-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0008_user_suspended_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='nickname',
            field=models.CharField(blank=True, help_text='If set, the space will be displayed using this name.', max_length=150),
        ),
    ]
