# Generated by Django 2.1.4 on 2018-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0009_space_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_register',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
    ]
