# Generated by Django 2.1.4 on 2018-12-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0011_auto_20181218_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
