# Generated by Django 2.1.11 on 2019-09-04 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0013_auto_20190127_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='liaisons',
            field=models.ManyToManyField(blank=True, related_name='liaison_shows', to=settings.AUTH_USER_MODEL),
        ),
    ]
