# Generated by Django 2.1.12 on 2019-09-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0014_show_liaisons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_access',
            field=models.BooleanField(default=False, help_text='Has access to this administrative portal'),
        ),
    ]
