# Generated by Django 2.1.12 on 2019-09-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0015_user_admin_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'permissions': (('change_current_season', 'Can change the current season'),)},
        ),
    ]
