# Generated by Django 2.1.12 on 2019-09-18 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0016_auto_20190918_0036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('modify_user', 'Can modify user account details'),)},
        ),
    ]
