# Generated by Django 2.1.12 on 2019-09-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0017_auto_20190918_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupProxy',
        ),
    ]
