# Generated by Django 2.2.6 on 2019-10-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0018_delete_groupproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='huid',
            field=models.CharField(default='', help_text='If you do not have or do not wish to provide your HUID, you may enter "0" into this field.', max_length=8, verbose_name='HUID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
    ]
