# Generated by Django 2.2.6 on 2019-10-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0018_delete_groupproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='creator_credit',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='show',
            name='group_affiliation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('executive', models.BooleanField(default=True)),
                ('advisor', models.BooleanField(default=False)),
                ('assistant', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Show')),
            ],
        ),
    ]
