# Generated by Django 2.2.6 on 2019-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0019_auto_20191022_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='group_affiliation',
        ),
        migrations.AddField(
            model_name='show',
            name='affiliation',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='show',
            name='prod_type',
            field=models.CharField(choices=[('play', 'Play'), ('musical', 'Musical or Opera'), ('dance', 'Dance Performance'), ('devised', 'Devised Piece'), ('workshop', 'Workshop'), ('other', 'Other')], default='play', max_length=30),
        ),
    ]
