# Generated by Django 2.2.6 on 2019-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0019_auto_20191018_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='huid',
            field=models.CharField(help_text='If you do not have or do not wish to provide a HUID, you may enter "0" into this field.', max_length=8, verbose_name='HUID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Graduation Year'),
        ),
    ]
