# Generated by Django 2.2.6 on 2019-10-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0002_auto_20191030_1650'),
        ('dramaorg', '0020_auto_20191030_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffMember',
        ),
    ]
