# Generated by Django 2.2.6 on 2019-10-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0021_delete_staffmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='affiliation',
            field=models.CharField(blank=True, help_text='Producing or sponsoring group, if applicable.', max_length=60, verbose_name='Sponsorship/Affiliation'),
        ),
        migrations.AlterField(
            model_name='show',
            name='creator_credit',
            field=models.CharField(blank=True, max_length=300, verbose_name='Author/Creator'),
        ),
        migrations.AlterField(
            model_name='show',
            name='prod_type',
            field=models.CharField(choices=[('play', 'Play'), ('musical', 'Musical or Opera'), ('dance', 'Dance Performance'), ('devised', 'Devised Piece'), ('workshop', 'Workshop'), ('other', 'Other')], default='play', max_length=30, verbose_name='Production Type'),
        ),
    ]
