# Generated by Django 2.2.6 on 2019-10-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0022_auto_20191031_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='creator_credit',
            field=models.CharField(max_length=300, verbose_name='Author/Creator'),
        ),
    ]
