# Generated by Django 2.2.6 on 2019-11-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0023_auto_20191031_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
    ]
