# Generated by Django 2.2.6 on 2019-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0024_auto_20191105_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='creator_credit',
            field=models.CharField(max_length=300, verbose_name='Author/Composer'),
        ),
    ]
