# Generated by Django 2.2.6 on 2020-01-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0025_auto_20191106_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ('-residency_starts', '-residency_ends'), 'permissions': (('change_current_season', 'Can change the current season'),)},
        ),
    ]
