# Generated by Django 2.2.6 on 2020-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0028_auto_20200115_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_affiliation',
            field=models.BooleanField(default=False, help_text='Display your affiliation with your name?'),
        ),
    ]
