# Generated by Django 2.2.6 on 2020-01-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0031_user_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=True, verbose_name='Subscribe to the Newsletter'),
        ),
    ]
