# Generated by Django 2.2.6 on 2020-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0032_auto_20200123_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=True, help_text='Uncheck this to unsubscribe.', verbose_name='Subscribe to the Newsletter'),
        ),
    ]
