# Generated by Django 2.2.24 on 2022-05-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0035_auto_20220430_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
