# Generated by Django 2.2.24 on 2022-05-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0036_auto_20220430_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
