# Generated by Django 2.1.11 on 2019-09-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicityinfo',
            name='show_blurb',
        ),
        migrations.AddField(
            model_name='publicityinfo',
            name='blurb',
            field=models.TextField(blank=True, verbose_name='About the Show'),
        ),
        migrations.AlterField(
            model_name='publicityinfo',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email for Publicity'),
        ),
        migrations.AlterField(
            model_name='publicityinfo',
            name='credits',
            field=models.TextField(blank=True, help_text='Include authorial credits, as well as directors and producers.', verbose_name='Masthead Credits'),
        ),
    ]
