# Generated by Django 2.1.11 on 2019-09-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0002_auto_20190905_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='publicityinfo',
            name='runtime',
            field=models.CharField(blank=True, help_text='E.g. 2 hours with a 10-minute intermission', max_length=80),
        ),
        migrations.AddField(
            model_name='performancedate',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicity.PublicityInfo'),
        ),
    ]
