# Generated by Django 2.1.11 on 2019-09-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0005_auto_20190905_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancedate',
            options={'ordering': ('performance',)},
        ),
        migrations.RemoveField(
            model_name='showperson',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='performancedate',
            unique_together={('show', 'performance')},
        ),
    ]
