# Generated by Django 2.1.11 on 2019-09-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0006_auto_20190905_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showperson',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='showperson',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
