# Generated by Django 2.1.11 on 2019-09-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0007_auto_20190905_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='showperson',
            unique_together={('order', 'show', 'type')},
        ),
    ]
