# Generated by Django 2.1.11 on 2019-09-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0009_auto_20190905_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='position',
            field=models.CharField(max_length=120),
        ),
    ]
