# Generated by Django 2.1.11 on 2019-09-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0010_auto_20190905_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='email',
            field=models.EmailField(blank=True, help_text='This will not be shown publicly.', max_length=254),
        ),
        migrations.AlterField(
            model_name='showperson',
            name='phone',
            field=models.CharField(blank=True, help_text='This will not be shown publicly.', max_length=20),
        ),
    ]
