# Generated by Django 2.1.11 on 2019-09-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0011_auto_20190905_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showperson',
            options={'ordering': ('type', 'order')},
        ),
        migrations.AlterField(
            model_name='showperson',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='showperson',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hidden'), (1, 'Staff'), (2, 'Cast')], db_index=True, default=0),
        ),
    ]
