# Generated by Django 2.1.11 on 2019-09-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0012_auto_20190906_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='position',
            field=models.CharField(max_length=120, verbose_name='Role or Position'),
        ),
        migrations.AlterUniqueTogether(
            name='showperson',
            unique_together=set(),
        ),
    ]
