# Generated by Django 2.1.11 on 2019-09-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0013_auto_20190906_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0),
        ),
    ]
