# Generated by Django 2.1.12 on 2019-09-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0014_auto_20190906_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicityinfo',
            name='public_page',
            field=models.URLField(blank=True),
        ),
    ]
