# Generated by Django 2.1.12 on 2019-09-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0015_publicityinfo_public_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicityinfo',
            old_name='public_page',
            new_name='website_page',
        ),
    ]
