# Generated by Django 2.1.12 on 2019-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0016_auto_20190914_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancedate',
            name='note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
