# Generated by Django 2.1.12 on 2019-09-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0017_performancedate_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showperson',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Role or Position'),
        ),
    ]
