# Generated by Django 2.1.12 on 2019-09-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0020_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='note',
            field=models.TextField(blank=True, help_text='This will not be published.', verbose_name='Note for the Editor'),
        ),
    ]
