# Generated by Django 2.1.12 on 2019-09-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0021_auto_20190921_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-start_date', '-end_date', '-submitted')},
        ),
        migrations.AddField(
            model_name='announcement',
            name='graphic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(help_text='Do not include in the newsletter after this date.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(help_text='Do not include in the newsletter before this date.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Submitting user'),
        ),
    ]
