# Generated by Django 2.1.12 on 2019-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0022_auto_20190921_2241_squashed_0024_auto_20190922_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicityinfo',
            name='band_term',
            field=models.CharField(choices=[('', 'Not Applicable'), ('Band', 'Band'), ('Orchestra', 'Orchestra'), ('Musicians', 'Musicians')], default='', max_length=20, verbose_name='Term for Pit Musicians'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='graphic',
            field=models.ImageField(blank=True, help_text="Optional graphic to include with your message. Graphics may be ommitted at the editor's discretion.", upload_to='publicity/announcements/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='showperson',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hidden'), (1, 'Staff'), (2, 'Cast'), (3, 'Band')], db_index=True, default=0),
        ),
    ]
