# Generated by Django 2.1.12 on 2019-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0023_auto_20190924_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicityinfo',
            name='ticket_link',
            field=models.URLField(blank=True),
        ),
    ]
