# Generated by Django 2.1.12 on 2019-09-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0023_auto_20190922_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='graphic',
            field=models.ImageField(blank=True, help_text='Optional graphic to include with your message.', upload_to='publicity/announcements/%Y/%m/%d/'),
        ),
    ]
