# Generated by Django 2.1.12 on 2019-09-24 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0024_publicityinfo_ticket_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showperson',
            options={'ordering': ('type', 'order', 'pk')},
        ),
    ]
