# Generated by Django 2.1.12 on 2019-09-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0025_auto_20190924_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicityinfo',
            name='band_term',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('Band', 'Band'), ('Orchestra', 'Orchestra'), ('Musicians', 'Musicians')], default='', max_length=20, verbose_name='Term for Pit Musicians'),
        ),
    ]
