# Generated by Django 2.2.6 on 2020-01-10 22:38
# RunPython added manually

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from django.contrib.auth import get_user_model
from django.utils.text import slugify

def migrate_people(apps, schema_editor):
    ShowPerson = apps.get_model("publicity", "ShowPerson")
    User = get_user_model()

    for i in ShowPerson.objects.all():
        user = None
        if i.email:
            user = User.objects.filter(email__iexact=i.email).first()
        if not user:
            fname, _, lname = i.name.split(" (")[0].rpartition(" ")
            email = i.email or "{}.{}-{}@DUMMY.hrdctheater.org".format(
                slugify(i.name), i.year or "0", i.id)
            try:
                user, created = User.objects.get_or_create(
                    first_name__iexact=fname, last_name__iexact=lname,
                    defaults={
                        "first_name": fname,
                        "last_name": lname,
                        "year": i.year,
                        "email": email,
                        "phone": i.phone,
                        "source": "publicity-migration",
                    })
            except User.MultipleObjectsReturned:
                user = User.objects.filter(first_name__iexact=fname,
                                           last_name__iexact=lname).first()
        i.person_id = user.id
        i.save()

def reverse_people(apps, schema_editor):
    ShowPerson = apps.get_model("publicity", "ShowPerson")
    User = get_user_model()

    for i in ShowPerson.objects.all():
        i.name = str(i.person)
        i.year = i.person.year
        i.email = i.person.email
        i.phone = i.person.phone
        i.save()

class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicity', '0026_auto_20190924_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='showperson',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_people, reverse_people),
        migrations.AlterField(
            model_name='showperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
