# Generated by Django 2.2.6 on 2020-01-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicity', '0028_auto_20200110_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-end_date', 'start_date', '-submitted')},
        ),
    ]
