# Generated by Django 2.1.11 on 2019-09-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dramaorg', '0014_show_liaisons'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_info', to='dramaorg.Show')),
            ],
            options={
                'verbose_name': 'Finance-Enabled Show',
            },
        ),
    ]
