# Generated by Django 2.1.11 on 2019-09-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Planned'), (1, 'Applied'), (10, 'Confirmed'), (11, 'Rejected'), ('Administrative Statuses', ((91, 'Funds Received'), (92, 'A.R.T. Grant')))], default=0),
        ),
    ]
