# Generated by Django 2.1.11 on 2019-09-12 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190911_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(10, 'Administrative'), (20, 'Production'), (50, 'Other')], default=10)),
                ('name', models.CharField(max_length=80)),
                ('estimate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('reported', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceInfo')),
            ],
            options={
                'verbose_name': 'Budget Expense Item',
            },
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Grant/Income', 'verbose_name_plural': 'Grants and Income'},
        ),
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Planned'), (1, 'Applied'), (51, 'Received'), ('Administrative Statuses', ((91, 'Confirmed (Funds Received)'), (92, 'A.R.T. Grant'))), (11, 'Rejected')], default=0),
        ),
    ]
