# Generated by Django 2.1.11 on 2019-09-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20190911_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetexpense',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
