# Generated by Django 2.1.11 on 2019-09-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20190911_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('-status',), 'verbose_name': 'Grant/Income', 'verbose_name_plural': 'Grants and Income'},
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='budgetexpense',
            name='reported',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
