# Generated by Django 2.1.11 on 2019-09-12 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20190911_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='amount_received',
            new_name='received',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='amount_requested',
            new_name='requested',
        ),
    ]
