# Generated by Django 2.1.11 on 2019-09-12 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20190912_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetexpense',
            options={'ordering': ('category',), 'verbose_name': 'Budget Expense Item'},
        ),
    ]
