# Generated by Django 2.1.11 on 2019-09-12 17:32

from django.db import migrations, models
import django.db.models.deletion
import finance.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20190912_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Purchased'), ('Reimbursement', ((51, 'Requested'), (52, 'Processed'))), ('P-Card', ((62, 'Confirmed'),))], default=0)),
                ('purchased_using', models.BooleanField(choices=[(False, 'P-Card'), (True, 'Personal Funds')])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_purchased', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('receipt', models.FileField(blank=True, upload_to=finance.models.Expense.upload_destination)),
                ('item', models.CharField(max_length=255)),
                ('purchaser_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('reimburse_via_mail', models.BooleanField(default=False, help_text='Does the reimbursement check need to be mailed?')),
                ('mailing_address', models.TextField(blank=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinanceInfo')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.BudgetExpense')),
            ],
        ),
    ]
