# Generated by Django 2.1.12 on 2019-09-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('finance', '0016_expense_check_number'), ('finance', '0017_auto_20190920_0003'), ('finance', '0018_auto_20190920_0006')]

    dependencies = [
        ('finance', '0015_auto_20190919_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='check_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Check #'),
        ),
    ]
