# Generated by Django 2.1.12 on 2019-09-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_auto_20190920_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceInfoExpenses',
        ),
    ]
