# Generated by Django 2.2.6 on 2020-01-25 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_auto_20200125_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetexpense',
            options={'ordering': ('category', 'pk'), 'verbose_name': 'Budgeted Expense Subcategory', 'verbose_name_plural': 'Budgeted Expense Subcategories'},
        ),
    ]
