# Generated by Django 2.2.6 on 2020-01-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_auto_20200125_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinfo',
            name='imported_budget',
            field=models.BooleanField(default=False),
        ),
    ]
