# Generated by Django 2.2.6 on 2020-01-26 07:25

from django.db import migrations, models
import django.db.models.deletion
import dramaorg.models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_financeinfo_imported_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=dramaorg.models._get_year)),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='financeinfo',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.Settlement'),
        ),
    ]
