# Generated by Django 2.2.6 on 2020-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_auto_20200126_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeinfo',
            name='include_royalties',
            field=models.BooleanField(default=True, verbose_name="Royalties come out of this season's box office revenue"),
        ),
    ]
