# Generated by Django 2.2.6 on 2020-01-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_financeinfo_include_royalties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeinfo',
            name='include_royalties',
        ),
        migrations.AddField(
            model_name='financeinfo',
            name='ignore_royalties',
            field=models.BooleanField(default=False, help_text="If checked, don't count royalties against the revenue.", verbose_name='Ignore Royalties'),
        ),
    ]
