# Generated by Django 2.2.6 on 2020-01-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0030_auto_20200126_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='club_budget_grant',
        ),
        migrations.AddField(
            model_name='settlement',
            name='club_budget',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='A.R.T. grant towards organization expenses.', max_digits=7),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='locked',
            field=models.BooleanField(default=False, help_text='Prevent staff members of shows in this settlement from adding, modifying, or updating their budget, income, and expenses.'),
        ),
    ]
