"""
Django settings for hrdc project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.contrib import messages

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '100lj0ceb%u-^n*)a%8xh()iml9neaz4jn!h548$#z7nf9!56)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', ".ngrok.io"]


# Application definition

INSTALLED_APPS = [
    'suit',
    'config',
    'emailtracker',
    'basetemplates',
    'hrdc',
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dramaorg',
    'casting',
    'bootstrapform',
    'anymail',
    'channels',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "hrdc.routing.channel_routing",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hrdc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'basetemplates.context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'hrdc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CSRF_USE_SESSIONS = True

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Eastern'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

AUTH_USER_MODEL = "dramaorg.User"

SHOW_MODEL = "dramaorg.Show"
SPACE_MODEL = "dramaorg.Space"
BUILDING_MODEL = "dramaorg.Building"

ANYMAIL = {
    "MAILGUN_API_KEY": "key-1113ec6d3ccf6f9419ef02fb6e3cf18c",
    "MAILGUN_SENDER_DOMAIN": "aolkin.me"
}
#EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = "Development Application <devtest@aolkin.me>"

CONFIGURATION_APP_TITLE = "Global Settings"

ADMIN_SITE_TITLE = "HRDC Apps"

ADMIN_GROUP_NAME = "HRDC Board"

LOGIN_URL = "dramaorg:login"
LOGOUT_URL = "dramaorg:logout"
LOGIN_REDIRECT_URL = "dramaorg:index"
LOGOUT_REDIRECT_URL = LOGIN_URL

BT_SITE_TITLE = "HRDC Apps"
BT_FAVICON_URL = "https://hrdctheater.com/wp-content/uploads/2016/02/cropped-HRDC-Logo-2-32x32.png"
BT_BOOTSTRAP_VERSION = "4.0.0-alpha.6"
BT_BOOTSTRAP_CSS_INTEGRITY = "sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
BT_BOOTSTRAP_JS_INTEGRITY = "sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
BT_TETHER_VERSION = "1.4.0"
BT_TETHER_INTEGRITY = "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"

BT_FOOTER_OWNER = "Harvard-Radcliffe Dramatic Club"
BT_FOOTER_SITE = "http://hrdctheater.com"
BT_HEADER_IMAGE = "logo.png"
BT_HEADER_URL = "dramaorg:index"

CASTING_IS_COMMON = True

ACTIVE_SEASON_KEY = "season"
ACTIVE_YEAR_KEY = "year"
