# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.SPACE_MODEL),
        migrations.swappable_dependency(settings.SHOW_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('done', 'Auditioned')], default='waiting', max_length=20)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CastingMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callback_description', models.TextField(blank=True)),
                ('cast_list_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('callback_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Space')),
            ],
        ),
        migrations.CreateModel(
            name='CastingReleaseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_callbacks', models.DateTimeField(blank=True, null=True)),
                ('publish_casts', models.DateTimeField(blank=True, null=True)),
                ('signing_opens', models.DateTimeField(blank=True, null=True)),
                ('second_signing_opens', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Casting Release Settings',
                'verbose_name_plural': 'Casting Release Settings',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('callback_description', models.TextField(blank=True)),
                ('allowed_signers', models.PositiveSmallIntegerField(default=1)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(choices=[('Common Times', ((datetime.time(18, 0), '06:00 PM'), (datetime.time(21, 0), '09:00 PM'), (datetime.time(0, 0), '12:00 AM'), (datetime.time(23, 30), '11:30 PM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(19, 0), '07:00 PM'))), ('All Times', ((datetime.time(9, 0), '09:00 AM'), (datetime.time(9, 30), '09:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(13, 30), '01:30 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(14, 30), '02:30 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(15, 30), '03:30 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(16, 30), '04:30 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(17, 30), '05:30 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(18, 30), '06:30 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(19, 30), '07:30 PM'), (datetime.time(20, 0), '08:00 PM'), (datetime.time(20, 30), '08:30 PM'), (datetime.time(21, 0), '09:00 PM'), (datetime.time(21, 30), '09:30 PM'), (datetime.time(22, 0), '10:00 PM'), (datetime.time(22, 30), '10:30 PM'), (datetime.time(23, 0), '11:00 PM'), (datetime.time(23, 30), '11:30 PM'), (datetime.time(0, 0), '12:00 AM')))])),
                ('end', models.TimeField(choices=[('Common Times', ((datetime.time(18, 0), '06:00 PM'), (datetime.time(21, 0), '09:00 PM'), (datetime.time(0, 0), '12:00 AM'), (datetime.time(23, 30), '11:30 PM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(19, 0), '07:00 PM'))), ('All Times', ((datetime.time(9, 0), '09:00 AM'), (datetime.time(9, 30), '09:30 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(10, 30), '10:30 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(11, 30), '11:30 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(12, 30), '12:30 PM'), (datetime.time(13, 0), '01:00 PM'), (datetime.time(13, 30), '01:30 PM'), (datetime.time(14, 0), '02:00 PM'), (datetime.time(14, 30), '02:30 PM'), (datetime.time(15, 0), '03:00 PM'), (datetime.time(15, 30), '03:30 PM'), (datetime.time(16, 0), '04:00 PM'), (datetime.time(16, 30), '04:30 PM'), (datetime.time(17, 0), '05:00 PM'), (datetime.time(17, 30), '05:30 PM'), (datetime.time(18, 0), '06:00 PM'), (datetime.time(18, 30), '06:30 PM'), (datetime.time(19, 0), '07:00 PM'), (datetime.time(19, 30), '07:30 PM'), (datetime.time(20, 0), '08:00 PM'), (datetime.time(20, 30), '08:30 PM'), (datetime.time(21, 0), '09:00 PM'), (datetime.time(21, 30), '09:30 PM'), (datetime.time(22, 0), '10:00 PM'), (datetime.time(22, 30), '10:30 PM'), (datetime.time(23, 0), '11:00 PM'), (datetime.time(23, 30), '11:30 PM'), (datetime.time(0, 0), '12:00 AM')))])),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.CastingMeta')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.Space')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Audition'), (1, 'Callback')], default=0)),
                ('day', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signing',
            fields=[
                ('callback_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='casting.Callback')),
                ('order', models.PositiveSmallIntegerField()),
                ('response', models.NullBooleanField()),
            ],
            options={
                'ordering': ('character__show', 'character', 'order'),
            },
            bases=('casting.callback',),
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='release_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.CastingReleaseMeta'),
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='casting_meta', to='dramaorg.Show'),
        ),
        migrations.AddField(
            model_name='callback',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callback',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.Character'),
        ),
        migrations.AlterModelOptions(
            name='castingmeta',
            options={'verbose_name': 'Show'},
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='release_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.CastingReleaseMeta', verbose_name='Casting Release Settings'),
        ),
        migrations.AlterModelOptions(
            name='castingmeta',
            options={'verbose_name': 'Casting Information for Show'},
        ),
        migrations.RemoveField(
            model_name='castingmeta',
            name='callback_location',
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='callback_slots',
            field=models.ManyToManyField(blank=True, to='casting.Slot'),
        ),
        migrations.AlterModelOptions(
            name='castingmeta',
            options={'verbose_name': 'Casting Information', 'verbose_name_plural': 'Casting Information'},
        ),
        migrations.RemoveField(
            model_name='castingmeta',
            name='callback_slots',
        ),
    ]
