# Generated by Django 2.0 on 2017-12-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_squashed_0021_auto_20171228_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingreleasemeta',
            options={'verbose_name': 'Casting Release Group'},
        ),
    ]
