# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0001_initial_squashed_0014_auto_20170710_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='day',
            field=models.DateField(),
        ),
    ]
