# Generated by Django 2.0 on 2018-01-04 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dramaorg.models


class Migration(migrations.Migration):

    replaces = [('casting', '0003_auto_20180103_2319'), ('casting', '0004_auto_20180103_2353')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casting', '0002_auto_20171228_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorSeasonMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=dramaorg.models._get_year)),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3)),
                ('conflicts', models.TextField(blank=True, help_text='Please list any recurring or major conflicts for this season.')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='audition',
            name='tech_interest',
            field=models.TextField(blank=True, help_text='What backstage or technical fields are you interested in?', verbose_name='Technical Interests'),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='callback_description',
            field=models.TextField(blank=True, help_text='Extra information about all callbacks (location, date, etc).', verbose_name='Callback Information'),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='cast_list_description',
            field=models.TextField(blank=True, help_text='Extra information to display with the cast list. Include shows you cannot share actors with here.', verbose_name='Cast List Information'),
        ),
    ]
