# Generated by Django 2.0 on 2018-01-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0003_auto_20180103_2319_squashed_0004_auto_20180103_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorseasonmeta',
            name='conflicts',
            field=models.TextField(help_text='Please list any recurring or major conflicts for this season.'),
        ),
    ]
