# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0003_auto_20170711_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingreleasemeta',
            name='stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
