# Generated by Django 2.0 on 2018-01-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_auto_20180104_0022_squashed_0006_auto_20180104_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='busy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='casting.Audition'),
        ),
    ]
