# Generated by Django 2.0 on 2018-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0004_auto_20180104_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition',
            name='tech_interest',
            field=models.TextField(blank=True, default=None, help_text='What backstage or technical fields are you interested in?', null=True, verbose_name='Technical Interests'),
        ),
    ]
