# Generated by Django 2.0 on 2018-01-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_auto_20180104_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='sign_in_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actorseasonmeta',
            name='conflicts',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='audition',
            name='tech_interest',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Technical Interests'),
        ),
    ]
