# Generated by Django 2.0 on 2018-01-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0005_audition_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='called_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='audition',
            name='done_time',
            field=models.DateTimeField(null=True),
        ),
    ]
