# Generated by Django 2.0 on 2018-01-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0006_auto_20180106_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='hidden_for_signing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='castingreleasemeta',
            name='second_signing_opens',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signing closes'),
        ),
    ]
