# Generated by Django 2.0 on 2018-01-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0007_auto_20180112_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='audition_length',
            field=models.DurationField(null=True),
        ),
    ]
