# Generated by Django 2.0 on 2018-01-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0008_audition_audition_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='signing',
            name='alternate_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='callbacks_submitted',
            field=models.BooleanField(default=False, verbose_name='Callbacks'),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='cast_submitted',
            field=models.BooleanField(default=False, verbose_name='Full Cast'),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='first_cast_submitted',
            field=models.BooleanField(default=False, verbose_name='First-round Cast'),
        ),
    ]
