# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0008_auto_20170715_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingmeta',
            name='callbacks_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='cast_submitted',
            field=models.BooleanField(default=False, verbose_name='Full Cast List Submitted'),
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='first_cast_submitted',
            field=models.BooleanField(default=False, verbose_name='First-round Cast List Submitted'),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='callback_description',
            field=models.TextField(blank=True, help_text='Extra information about all callbacks (location, etc).', verbose_name='Callback Information'),
        ),
        migrations.AlterField(
            model_name='character',
            name='callback_description',
            field=models.TextField(blank=True, help_text='Extra information about callbacks for this character.', verbose_name='Character Callback Information'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Character Name'),
        ),
    ]
