# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0009_auto_20170716_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Show Contact Email'),
        ),
    ]
