# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0010_auto_20170716_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signing',
            name='notified_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signing',
            name='notified_second',
            field=models.BooleanField(default=False),
        ),
    ]
