# Generated by Django 2.1 on 2018-08-22 20:47

from django.db import migrations, models
import django.db.models.deletion
import dramaorg.models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0010_auto_20180817_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechReqPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=dramaorg.models._get_year)),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3)),
                ('name', models.CharField(max_length=36)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='num_tech_reqers',
            field=models.PositiveSmallIntegerField(default=999),
        ),
        migrations.AddField(
            model_name='signing',
            name='tech_req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casting.CastingMeta'),
        ),
        migrations.AddField(
            model_name='techreqpool',
            name='shows',
            field=models.ManyToManyField(to='casting.CastingMeta'),
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='tech_req_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='casting.TechReqPool', verbose_name='Contributes tech reqers to'),
        ),
    ]
