# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0011_auto_20170719_0309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signing',
            options={},
        ),
        migrations.RemoveField(
            model_name='signing',
            name='callback_ptr',
        ),
        migrations.AddField(
            model_name='character',
            name='added_during_callbacks',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='cast_list_description',
            field=models.TextField(blank=True, help_text='Extra information to display with the cast list.', verbose_name='Cast List Information'),
        ),
    ]
