# Generated by Django 2.1 on 2018-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('casting', '0012_auto_20180822_2217'), ('casting', '0013_auto_20180822_2219')]

    dependencies = [
        ('casting', '0011_auto_20180822_1647'),
    ]

    operations = [
    ]
