# Generated by Django 2.1 on 2018-08-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0011_auto_20180822_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='castingmeta',
            name='num_tech_reqers',
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='takes_tech_reqers',
            field=models.PositiveSmallIntegerField(default=999),
        ),
    ]
