# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casting', '0012_auto_20170720_1729'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signing',
        ),
    ]
