# Generated by Django 2.1 on 2018-08-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0012_auto_20180822_2217_squashed_0013_auto_20180822_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techreqpool',
            options={'verbose_name': 'Tech Req Show Pool'},
        ),
        migrations.AddField(
            model_name='techreqpool',
            name='exempt_year',
            field=models.PositiveSmallIntegerField(help_text='Actors in this year do not need to contribute to this pool.', null=True),
        ),
    ]
