# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casting', '0013_auto_20170720_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('response', models.NullBooleanField()),
                ('notified_first', models.BooleanField(default=False)),
                ('notified_second', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casting.Character')),
            ],
            options={
                'ordering': ('character__show', 'character', 'order'),
            },
        ),
    ]
