# Generated by Django 2.1 on 2018-08-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0013_auto_20180822_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmeta',
            name='num_tech_reqers',
            field=models.PositiveSmallIntegerField(default=999, help_text='How many tech reqers can this show have?', verbose_name='Tech Reqers Allowed'),
        ),
        migrations.AlterField(
            model_name='techreqpool',
            name='shows',
            field=models.ManyToManyField(help_text='Shows in this pool that need tech reqers.', to='casting.CastingMeta'),
        ),
    ]
