# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0014_signing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='added_during_callbacks',
        ),
        migrations.AddField(
            model_name='character',
            name='added_for_signing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='character',
            name='allowed_signers',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of actors allowed to sign, can be increased to cast ensemble roles.'),
        ),
    ]
