# Generated by Django 2.1 on 2018-08-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0014_auto_20180823_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingreleasemeta',
            name='second_signing_warning',
            field=models.DateTimeField(blank=True, help_text='Sends a reminder to unsigned actors at this time.', null=True, verbose_name='Signing closes warning'),
        ),
        migrations.AlterField(
            model_name='castingreleasemeta',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Auditions'), (1, 'Callback Lists Released'), (2, 'First-Round Casting Released'), (3, 'Cast Lists Released'), (4, 'Signing Open'), (5, 'Sent Signing Reminder'), (6, 'Alternate Signing Open')], default=0),
        ),
    ]
