# Generated by Django 2.1 on 2018-09-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0015_auto_20180823_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='allow_multiple_signatures',
            field=models.BooleanField(default=False),
        ),
    ]
