# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0016_auto_20170724_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingreleasemeta',
            name='prevent_advancement',
            field=models.BooleanField(default=False, help_text='If this is set, the stage will not advance automatically regardless of set times, until this is cleared.'),
        ),
    ]
