# Generated by Django 2.1 on 2018-12-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0017_auditioncastingmeta_techreqcastingmeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techreqpool',
            name='shows',
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='exempt_year',
            field=models.PositiveSmallIntegerField(help_text='Actors in this year do not need to sign for a tech req.', null=True),
        ),
        migrations.RemoveField(
            model_name='castingmeta',
            name='tech_req_pool',
        ),
        migrations.AddField(
            model_name='castingmeta',
            name='tech_req_pool',
            field=models.ManyToManyField(blank=True, related_name='_castingmeta_tech_req_pool_+', to='casting.CastingMeta', verbose_name='Actors must tech req on one of'),
        ),
        migrations.DeleteModel(
            name='TechReqPool',
        ),
    ]
