# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0017_castingreleasemeta_prevent_advancement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingreleasemeta',
            name='prevent_advancement',
            field=models.BooleanField(default=False, help_text='If this is set, the stage will not advance until it is cleared again, regardless of set times.'),
        ),
        migrations.AlterField(
            model_name='castingreleasemeta',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Auditions'), (1, 'Callback Lists Released'), (2, 'First-Round Casting Released'), (3, 'Cast Lists Released'), (4, 'Signing Open'), (5, 'Alternate Signing Open')], default=0),
        ),
    ]
