# Generated by Django 2.1 on 2018-12-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0018_auto_20181213_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingmeta',
            name='exempt_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Actors in this year do not need to sign for a tech req.', null=True),
        ),
        migrations.AlterField(
            model_name='castingmeta',
            name='tech_req_pool',
            field=models.ManyToManyField(blank=True, to='casting.CastingMeta', verbose_name='Actors must tech req on one of'),
        ),
    ]
