# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0019_auto_20170726_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callback',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='signing',
            name='notified_first',
        ),
        migrations.RemoveField(
            model_name='signing',
            name='notified_second',
        ),
        migrations.AddField(
            model_name='signing',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
    ]
