# Generated by Django 2.0 on 2017-12-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0020_auto_20170727_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dramaorg.Space'),
        ),
    ]
