# Generated by Django 2.1.4 on 2019-01-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0020_auto_20181213_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='signing',
            name='signed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
