# Generated by Django 2.1.4 on 2019-01-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0021_signing_signed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingreleasemeta',
            name='stage',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Auditions'), (1, 'Callback Lists Released'), (2, 'First-Round Casting Released'), (3, 'Cast Lists Released'), (4, 'Signing Open'), (5, 'Sent Signing Reminder'), (6, 'Signing Closed')], default=0),
        ),
    ]
