# Generated by Django 2.1.5 on 2019-02-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0023_auto_20190126_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signing',
            name='signed_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
