# Generated by Django 2.1.11 on 2019-09-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0025_auto_20190806_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorseasonmeta',
            name='conflicts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
