# Generated by Django 2.1.12 on 2019-09-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0026_auto_20190903_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingmeta',
            options={'permissions': (('view_unreleased_callbacks', 'Can view unreleased callbacks'), ('view_unreleased_cast', 'Can view unreleased cast')), 'verbose_name': 'Casting-Enabled Show'},
        ),
    ]
