# Generated by Django 2.2.6 on 2020-01-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0029_auto_20190918_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='castingreleasemeta',
            options={'permissions': (('view_first_cast_lists', 'Can view first-round cast lists'), ('update_castingreleasemeta_stage', 'Can manually set the stage')), 'verbose_name': 'Casting Release Group'},
        ),
        migrations.AddField(
            model_name='castingreleasemeta',
            name='disable_signing',
            field=models.BooleanField(default=False, help_text='Checking this will prevent actors from signing.'),
        ),
    ]
