# Generated by Django 2.2.6 on 2020-01-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0030_auto_20200118_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castingreleasemeta',
            name='disable_signing',
            field=models.BooleanField(default=False, help_text='Checking this will temporarily prevent actors from signing.'),
        ),
    ]
