# Generated by Django 2.2.6 on 2020-01-30 23:21

from django.db import migrations, models
import dramaorg.models

def add_season(apps, schema_editor):
    CastingReleaseMeta = apps.get_model("casting", "CastingReleaseMeta")
    for i in CastingReleaseMeta.objects.all():
        if i.castingmeta_set.exists():
            i.year = i.castingmeta_set.all().first().show.year
            i.season = i.castingmeta_set.all().first().show.season
            i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('casting', '0031_auto_20200118_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='castingreleasemeta',
            name='season',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3),
        ),
        migrations.AddField(
            model_name='castingreleasemeta',
            name='year',
            field=models.PositiveSmallIntegerField(default=dramaorg.models._get_year),
        ),
        migrations.RunPython(add_season),
    ]
