# Generated by Django 2.2.24 on 2022-04-23 03:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casting', '0033_auto_20200204_1815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actorseasonmeta',
            unique_together={('year', 'season', 'actor')},
        ),
    ]
