# Generated by Django 2.1.5 on 2019-02-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.SlugField(unique=True, verbose_name='Short URL'),
        ),
    ]
