# Generated by Django 2.1.12 on 2019-09-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dramaorg', '0018_delete_groupproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archival_info', to='dramaorg.Show')),
            ],
        ),
    ]
