# Generated by Django 2.1.12 on 2019-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalinfo',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
