# Generated by Django 2.1.12 on 2019-10-17 15:15

import archive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivalinfo_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.FileField(upload_to=archive.models.ExtraFile.upload_destination)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field='height', upload_to=archive.models.ProductionPhoto.upload_destination, width_field='width')),
            ],
        ),
        migrations.AddField(
            model_name='archivalinfo',
            name='poster',
            field=models.FileField(blank=True, upload_to=archive.models.ArchivalInfo.pub_destination),
        ),
        migrations.AddField(
            model_name='archivalinfo',
            name='program',
            field=models.FileField(blank=True, upload_to=archive.models.ArchivalInfo.pub_destination),
        ),
        migrations.AddField(
            model_name='productionphoto',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ArchivalInfo'),
        ),
        migrations.AddField(
            model_name='extrafile',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='archive.ArchivalInfo'),
        ),
    ]
