# Generated by Django 2.1.12 on 2019-10-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_auto_20191017_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivalinfo',
            options={'verbose_name': 'Show in archive', 'verbose_name_plural': 'Shows in Archive'},
        ),
        migrations.RenameField(
            model_name='extrafile',
            old_name='f',
            new_name='file',
        ),
    ]
