# Generated by Django 2.1.12 on 2019-10-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_auto_20191017_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionphoto',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionphoto',
            name='width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
