# Generated by Django 2.2.6 on 2019-10-17 16:57

import archive.models
from django.db import migrations
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_auto_20191017_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionphoto',
            name='img',
            field=django_thumbs.fields.ImageThumbsField(height_field='height', sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '320x240'}, {'code': 'small', 'resize': 'scale', 'wxh': '400x400'}, {'code': 'medium', 'resize': 'scale', 'wxh': '800x800'}, {'code': 'large', 'resize': 'scale', 'wxh': '1200x1200'}, {'code': 'xl', 'resize': 'scale', 'wxh': '2000x2000'}), upload_to=archive.models.ProductionPhoto.upload_destination, width_field='width'),
        ),
    ]
