# Generated by Django 2.2.6 on 2019-10-17 17:10

import archive.models
from django.db import migrations, models
import django_thumbs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_auto_20191017_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafile',
            name='credit',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extrafile',
            name='description',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionphoto',
            name='credit',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionphoto',
            name='img',
            field=django_thumbs.fields.ImageThumbsField(height_field='height', sizes=({'code': 'thumb', 'resize': 'crop', 'wxh': '320x240'}, {'code': 'preview', 'resize': 'scale', 'wxh': '1200x1200'}), upload_to=archive.models.ProductionPhoto.upload_destination, width_field='width'),
        ),
    ]
