# Generated by Django 2.2.6 on 2019-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_auto_20191017_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionphoto',
            name='allow_in_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
