# Generated by Django 2.2.6 on 2019-10-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_productionphoto_allow_in_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionphoto',
            old_name='allow_in_newsletter',
            new_name='allow_in_publicity',
        ),
    ]
