# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=254)),
                ('subject', models.CharField(max_length=80)),
                ('msg', models.BinaryField()),
                ('msg_id', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('ident', models.CharField(max_length=60)),
                ('sent', models.DateTimeField(null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
