# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedemail',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='queuedemail',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
