# Generated by Django 2.2.6 on 2019-10-22 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dramaorg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dramaorg', '0019_auto_20191022_1606'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_size', models.CharField(max_length=80)),
                ('cast_breakdown', models.CharField(max_length=80)),
                ('personnel_note', models.TextField()),
                ('calendar', models.FileField(upload_to='')),
                ('budget', models.FileField(help_text='Please submit a single document with separate budgets for each venue you are applying to.', upload_to='')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dramaorg.Show')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('resume', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VenueApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=dramaorg.models._get_year)),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3)),
                ('prelim_due', models.DateTimeField()),
                ('full_due', models.DateTimeField()),
                ('instructions', models.TextField()),
                ('managers', models.ManyToManyField(blank=True, help_text='These users will get application submission notifications.', related_name='venue_manager', to=settings.AUTH_USER_MODEL)),
                ('readers', models.ManyToManyField(blank=True, help_text='These users can view submitted applications.', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dramaorg.Space')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflicts', models.TextField(blank=True)),
                ('submission', models.FileField(null=True, upload_to='', verbose_name='Statement or design plan')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.Application')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='venueapp.Resume')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dramaorg.StaffMember')),
            ],
        ),
        migrations.CreateModel(
            name='SlotPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(default=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.Application')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.VenueApp')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.VenueApp')),
            ],
        ),
    ]
