# Generated by Django 2.2.6 on 2019-10-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0002_auto_20191030_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrole',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='staffrole',
            name='assistant',
        ),
        migrations.AddField(
            model_name='staffrole',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Author'), (10, 'Executive'), (20, 'Designer'), (30, 'Technician'), (40, 'Assistant'), (50, 'Advisor'), (60, 'Other')], default=10),
        ),
        migrations.AlterField(
            model_name='staffrole',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
