# Generated by Django 2.2.6 on 2019-10-31 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0003_auto_20191030_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'ordering': ('category', 'name')},
        ),
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='full_submitted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pre_submitted',
            field=models.DateTimeField(null=True),
        ),
    ]
