# Generated by Django 2.2.6 on 2019-10-31 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0004_auto_20191030_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='show',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dramaorg.Show'),
        ),
    ]
