# Generated by Django 2.2.6 on 2019-10-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0006_auto_20191031_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrole',
            name='other',
        ),
        migrations.AddField(
            model_name='staffrole',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
