# Generated by Django 2.2.6 on 2019-10-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0008_auto_20191031_0521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together={('show', 'person')},
        ),
    ]
