# Generated by Django 2.2.6 on 2019-10-31 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0010_auto_20191031_0721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together=set(),
        ),
    ]
