# Generated by Django 2.2.6 on 2019-11-01 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0012_auto_20191031_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableResidency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('type', models.BooleanField(choices=[(False, 'Available Range'), (True, 'Single Slot')])),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.VenueApp')),
            ],
        ),
        migrations.RemoveField(
            model_name='availableslot',
            name='venue',
        ),
        migrations.AlterField(
            model_name='slotpreference',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venueapp.AvailableResidency'),
        ),
        migrations.DeleteModel(
            name='AvailableDates',
        ),
        migrations.DeleteModel(
            name='AvailableSlot',
        ),
    ]
