# Generated by Django 2.2.6 on 2019-11-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0013_auto_20191101_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableresidency',
            options={'ordering': ('start',)},
        ),
        migrations.AlterField(
            model_name='availableresidency',
            name='type',
            field=models.BooleanField(choices=[(False, 'Available Range'), (True, 'Single Residency')]),
        ),
    ]
