# Generated by Django 2.2.6 on 2019-11-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0014_auto_20191101_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotpreference',
            name='length_description',
        ),
        migrations.AddField(
            model_name='application',
            name='length_description',
            field=models.TextField(blank=True, help_text='Please elaborate on your preferences for residency length, if necessary.'),
        ),
        migrations.AlterField(
            model_name='slotpreference',
            name='slot',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='venueapp.AvailableResidency'),
        ),
    ]
