# Generated by Django 2.2.6 on 2019-11-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0015_auto_20191101_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availableresidency',
            options={'ordering': ('start',), 'verbose_name_plural': 'Available Residencies'},
        ),
        migrations.AddField(
            model_name='budgetline',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DefaultBudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Income'), (10, 'Administrative Expense'), (20, 'Production Expense'), (50, 'Other Expense')], default=10)),
                ('name', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venueapp.VenueApp')),
            ],
            options={
                'ordering': ('venue', 'category'),
            },
        ),
    ]
