# Generated by Django 2.2.6 on 2019-11-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0016_auto_20191101_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultbudgetline',
            name='required',
        ),
    ]
