# Generated by Django 2.2.6 on 2019-11-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0018_auto_20191104_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueapp',
            name='question_instr',
        ),
        migrations.AddField(
            model_name='venueapp',
            name='contact_email',
            field=models.EmailField(default='', help_text='Displayed to applicants as the point of contact for this application.', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venueapp',
            name='budget_instr',
            field=models.TextField(blank=True, verbose_name='Budget Notes or Instructions'),
        ),
        migrations.AlterField(
            model_name='venueapp',
            name='residency_instr',
            field=models.TextField(blank=True, verbose_name='Residency Notes or Instructions'),
        ),
    ]
