# Generated by Django 2.2.6 on 2019-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0019_auto_20191104_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueapp',
            name='residency_instr',
            field=models.TextField(blank=True, verbose_name='Residency Description'),
        ),
    ]
