# Generated by Django 2.2.6 on 2019-11-05 08:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import dramaorg.models
import venueapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('dramaorg', '0024_auto_20191105_0312'),
        ('venueapp', '0020_auto_20191104_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='full_submitted',
            new_name='submitted',
        ),
        migrations.RenameField(
            model_name='venueapp',
            old_name='full_due',
            new_name='due',
        ),
        migrations.RemoveField(
            model_name='application',
            name='pre_submitted',
        ),
        migrations.RemoveField(
            model_name='venueapp',
            name='prelim_due',
        ),
        migrations.AlterField(
            model_name='application',
            name='script',
            field=models.FileField(blank=True, help_text='Only include for original or unknown works.', upload_to=venueapp.models.Application.upload_destination, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='seasonstaffmeta',
            name='resume',
            field=models.FileField(upload_to=venueapp.models.SeasonStaffMeta.upload_destination, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='attachment',
            field=models.FileField(blank=True, upload_to=venueapp.models.StaffMember.upload_destination, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.CreateModel(
            name='OldStyleApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=dramaorg.models._get_year)),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Winter'), (1, 'Spring'), (2, 'Summer'), (3, 'Fall')], default=3)),
                ('due', models.DateTimeField()),
                ('live', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=60)),
                ('url', models.URLField(blank=True)),
                ('download', models.FileField(blank=True, upload_to=venueapp.models.OldStyleApp.upload_destination)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dramaorg.Space')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
