# Generated by Django 2.2.6 on 2019-11-05 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0021_auto_20191105_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldstyleapp',
            name='name',
        ),
    ]
