# Generated by Django 2.2.6 on 2019-11-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0022_remove_oldstyleapp_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oldstyleapp',
            options={'verbose_name': 'Old-Style Application'},
        ),
        migrations.AlterModelOptions(
            name='slotpreference',
            options={'ordering': ('-app', 'ordering')},
        ),
        migrations.AlterModelOptions(
            name='staffrole',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Staff Role'},
        ),
        migrations.AlterModelOptions(
            name='venueapp',
            options={'verbose_name': 'Venue Application'},
        ),
    ]
