# Generated by Django 2.2.6 on 2019-11-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueapp', '0023_auto_20191105_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='band_size',
            field=models.CharField(max_length=80, verbose_name='Band/Orchestra Size'),
        ),
        migrations.AlterField(
            model_name='application',
            name='cast_breakdown',
            field=models.CharField(max_length=80, verbose_name='Cast Gender Breakdown'),
        ),
        migrations.AlterField(
            model_name='roleanswer',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
